//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.12

pub use super::blog::Entity as Blog;
pub use super::blog_tag::Entity as BlogTag;
pub use super::category::Entity as Category;
pub use super::tag::Entity as Tag;
pub use super::user::Entity as User;
